#version 460

const uint COLOR_SPACE_SRGB = 0;
const uint COLOR_SPACE_EXTENDED_SRGB_LINEAR = 1;
const uint COLOR_SPACE_HDR10_ST2084 = 2;

layout (local_size_x = 16, local_size_y = 16) in;

layout (constant_id = 0) const uint colorSpace = COLOR_SPACE_SRGB;

layout (binding = 0) uniform u
{
  ivec2 renderTargetSize;
  ivec2 cursorPos;
};

layout (binding = 1, rgba16f)  uniform image2D renderTargetRgba16F;
layout (binding = 1, rgba8)    uniform image2D renderTargetRgba8;
layout (binding = 1, rgb10_a2) uniform image2D renderTargetRgb10A2;

layout (binding = 2, rgba8) readonly uniform image2D cursor;

float srgbToLinear(float value)
{
  const float U = 0.04045;
  const float A = 12.92;
  const float C = 0.055;
  const float G = 2.4;

  if (value <= U)
  {
    return value / A;
  }
  else
  {
    return pow((value + C) / (1.0 + C), G);
  }
}

vec3 srgbToLinear(vec3 value)
{
  return vec3(
    srgbToLinear(value.r),
    srgbToLinear(value.g),
    srgbToLinear(value.b));
}

float linearToSrgb(float value)
{
  const float V = 0.0031308;
  const float A = 12.92;
  const float C = 0.055;
  const float G_INV = 1.0 / 2.4;

  if (value <= V)
  {
    return A * value;
  }
  else
  {
    return (1.0 + C) * pow(value, G_INV) - C;
  }
}

vec3 linearToSrgb(vec3 value)
{
  return vec3(
    linearToSrgb(value.r),
    linearToSrgb(value.g),
    linearToSrgb(value.b));
}

vec3 st2084ToLinear(vec3 value)
{
  // SMPTE ST 2084 perceptual quantizer (PQ) EOTF
  const float M1_INV = 8192.0 / 1305.0;
  const float M2_INV = 32.0 / 2523.0;
  const float C1 = 107.0 / 128.0;
  const float C2 = 2413.0 / 128.0;
  const float C3 = 2392.0 / 128.0;

  vec3 num = max(pow(value, vec3(M2_INV)) - C1, 0.0);
  vec3 den = C2 - C3 * pow(value, vec3(M2_INV));
  vec3 l = pow(num / den, vec3(M1_INV));
  vec3 c = 10000.0 * l;

  return c;
}

vec3 linearToSt2084(vec3 value)
{
  // SMPTE ST 2084 perceptual quantizer (PQ) inverse EOTF
  const float M1 = 1305.0 / 8192.0;
  const float M2 = 2523.0 / 32.0;
  const float C1 = 107.0 / 128.0;
  const float C2 = 2413.0 / 128.0;
  const float C3 = 2392.0 / 128.0;

  vec3 l = value / 10000.0;
  vec3 lM1 = pow(l, vec3(M1));
  vec3 num = C1 + C2 * lM1;
  vec3 den = 1.0 + C3 * lM1;
  vec3 n = pow(num / den, vec3(M2));

  return n;
}

vec3 bt709ToBt2020(vec3 value)
{
  // Matrix values from BT.2087-0
  const mat3 BT709_TO_BT2020 = mat3(
    0.6274, 0.0691, 0.0164,
    0.3293, 0.9195, 0.0880,
    0.0433, 0.0114, 0.8956
  );
  return BT709_TO_BT2020 * value;
}

void main()
{
  // TODO: Get this from the LG host
  const float WHITE_LEVEL_NITS = 250.0;

  // Read the cursor pixel to blend into the render target. This is sRGB
  // non-linear
  ivec2 invocationPos = ivec2(gl_GlobalInvocationID.x, gl_GlobalInvocationID.y);
  vec4 cursorPx = imageLoad(cursor, invocationPos);
  if (cursorPx.a == 0.0)
    return;

  // Read the current value in the render target. This is encoded according to
  // the configured color space
  ivec2 renderPos = cursorPos + invocationPos;
  if (renderPos.x >= renderTargetSize.x || renderPos.y >= renderTargetSize.y)
    return;

  vec4 renderTargetPx;
  switch (colorSpace)
  {
    case COLOR_SPACE_SRGB:
      renderTargetPx = imageLoad(renderTargetRgba8, renderPos);
      break;

    case COLOR_SPACE_EXTENDED_SRGB_LINEAR:
      renderTargetPx = imageLoad(renderTargetRgba16F, renderPos);
      break;

    case COLOR_SPACE_HDR10_ST2084:
      renderTargetPx = imageLoad(renderTargetRgb10A2, renderPos);
      break;
  }

  // Convert to linear space for blending
  cursorPx.rgb = srgbToLinear(cursorPx.rgb);

  switch (colorSpace)
  {
    case COLOR_SPACE_SRGB:
      renderTargetPx.rgb = srgbToLinear(renderTargetPx.rgb);
      break;

    case COLOR_SPACE_EXTENDED_SRGB_LINEAR:
      // Already linear
      break;

    case COLOR_SPACE_HDR10_ST2084:
      renderTargetPx.rgb = st2084ToLinear(renderTargetPx.rgb);
      break;
  }

  // Convert the cursor to the target colorimetry
  switch (colorSpace)
  {
    case COLOR_SPACE_SRGB:
      // Both BT.709. SDR so white level does not apply
      break;

    case COLOR_SPACE_EXTENDED_SRGB_LINEAR:
      // Both BT.709. Adjust cursor to match current white level
      const float REFERENCE_LUMINANCE_NITS = 80.0;
      cursorPx.rgb = cursorPx.rgb * WHITE_LEVEL_NITS / REFERENCE_LUMINANCE_NITS;
      break;

    case COLOR_SPACE_HDR10_ST2084:
      // Convert cursor from BT.709 (sRGB colors) to BT.2020 (HDR10 colors) and
      // adjust to match current white level
      cursorPx.rgb = bt709ToBt2020(cursorPx.rgb) * WHITE_LEVEL_NITS;
      break;
  }

  // Do the blend
  vec4 blendedPx = vec4(
    cursorPx.rgb * cursorPx.a + renderTargetPx.rgb * (1.0 - cursorPx.a),
    renderTargetPx.a + cursorPx.a);

  // Convert back to the target color space
  switch (colorSpace)
  {
    case COLOR_SPACE_SRGB:
      blendedPx.rgb = linearToSrgb(blendedPx.rgb);
      break;

    case COLOR_SPACE_EXTENDED_SRGB_LINEAR:
      // Output is linear
      break;

    case COLOR_SPACE_HDR10_ST2084:
      blendedPx.rgb = linearToSt2084(blendedPx.rgb);
      break;
  }

  // Save back to the render target
  switch (colorSpace)
  {
    case COLOR_SPACE_SRGB:
      imageStore(renderTargetRgba8, renderPos, blendedPx);
      break;

    case COLOR_SPACE_EXTENDED_SRGB_LINEAR:
      imageStore(renderTargetRgba16F, renderPos, blendedPx);
      break;

    case COLOR_SPACE_HDR10_ST2084:
      imageStore(renderTargetRgb10A2, renderPos, blendedPx);
      break;
  }
}
