/**
 * Looking Glass
 * Copyright © 2017-2024 The Looking Glass Authors
 * https://looking-glass.io
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation; either version 2 of the License, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc., 59
 * Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

#include "cursor.h"
#include "common/array.h"
#include "common/locking.h"
#include "common/util.h"

#include "vulkan_util.h"

#include <math.h>
#include <string.h>

// these headers are auto generated by cmake
#include "cursor_rgb.comp.spv.h"

typedef enum ShaderColorSpace
{
  SHADER_COLOR_SPACE_SRGB,
  SHADER_COLOR_SPACE_EXTENDED_SRGB_LINEAR,
  SHADER_COLOR_SPACE_HDR10_ST2084,
}
ShaderColorSpace;

struct UniformBuffer
{
  int32_t renderTargetSize[2];
  int32_t cursorPos[2];
};

struct CursorPos
{
  float x, y;
};

struct CursorSize
{
  float w, h;
};

struct Vulkan_Cursor
{
  LG_Lock           lock;
  LG_RendererCursor type;
  int               width;
  int               height;
  int               stride;
  uint8_t         * data;
  size_t            dataSize;
  bool              update;

  // cursor state
  bool              visible;
  LG_RendererRotate rotate;

  _Atomic(struct CursorPos)  pos;
  _Atomic(struct CursorPos)  hs;

  struct VkPhysicalDeviceMemoryProperties * memoryProperties;
  VkDevice              device;
  VkShaderModule        computeShader;
  VkCommandBuffer       commandBuffer;
  VkDescriptorPool      descriptorPool;
  VkDescriptorSetLayout descriptorSetLayout;
  VkDescriptorSet       descriptorSet;
  VkPipelineLayout      pipelineLayout;

  VkBuffer         uniformBuffer;
  VkDeviceMemory   uniformBufferMemory;
  void           * uniformBufferMap;

  VkPipeline       pipeline;

  VkImage          image;
  VkImageView      imageView;
  VkDeviceMemory   imageMemory;
  uint32_t         imageSize;
  VkBuffer         stagingBuffer;
  VkDeviceMemory   stagingMemory;
  void           * stagingMap;
};

static void freeUniformBuffer(Vulkan_Cursor * this)
{
  if (this->uniformBuffer)
  {
    vkDestroyBuffer(this->device, this->uniformBuffer, NULL);
    this->uniformBuffer = NULL;
  }

  if (this->uniformBufferMap)
  {
    vkUnmapMemory(this->device, this->uniformBufferMemory);
    this->uniformBufferMap = NULL;
  }

  if (this->uniformBufferMemory)
  {
    vkFreeMemory(this->device, this->uniformBufferMemory, NULL);
    this->uniformBufferMemory = NULL;
  }
}

static void freeImage(Vulkan_Cursor * this)
{
  if (this->imageView)
  {
    vkDestroyImageView(this->device, this->imageView, NULL);
    this->imageView = NULL;
  }

  if (this->image)
  {
    vkDestroyImage(this->device, this->image, NULL);
    this->image = NULL;
    this->imageSize = 0;
  }

  if (this->imageMemory)
  {
    vkFreeMemory(this->device, this->imageMemory, NULL);
    this->imageMemory = NULL;
  }

  if (this->stagingMap)
  {
    vkUnmapMemory(this->device, this->stagingMemory);
    this->stagingMap = NULL;
  }

  if (this->stagingBuffer)
  {
    vkDestroyBuffer(this->device, this->stagingBuffer, NULL);
    this->stagingBuffer = NULL;
  }

  if (this->stagingMemory)
  {
    vkFreeMemory(this->device, this->stagingMemory, NULL);
    this->stagingMemory = NULL;
  }
}

static bool createDescriptorSetLayout(Vulkan_Cursor * this)
{
  struct VkDescriptorSetLayoutBinding bindings[] =
  {
    {
      .binding = 0,
      .descriptorType = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER,
      .descriptorCount = 1,
      .stageFlags = VK_SHADER_STAGE_COMPUTE_BIT,
      .pImmutableSamplers = NULL
    },
    {
      .binding = 1,
      .descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_IMAGE,
      .descriptorCount = 1,
      .stageFlags = VK_SHADER_STAGE_COMPUTE_BIT,
      .pImmutableSamplers = NULL
    },
    {
      .binding = 2,
      .descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_IMAGE,
      .descriptorCount = 1,
      .stageFlags = VK_SHADER_STAGE_COMPUTE_BIT,
      .pImmutableSamplers = NULL
    }
  };

  this->descriptorSetLayout = vulkan_createDescriptorSetLayout(this->device,
      ARRAY_LENGTH(bindings), bindings);
  if (!this->descriptorSetLayout)
    return false;

  return true;
}

static bool createImage(Vulkan_Cursor * this)
{
  // Over-size the image to avoid reallocations when the shape changes
  uint32_t desiredSize = max(this->width, this->height);
  uint32_t actualSize = 64;
  while (actualSize < desiredSize)
    actualSize *= 2;
  if (actualSize <= this->imageSize)
    return true;

  freeImage(this);

  struct VkImageCreateInfo createInfo =
  {
    .sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO,
    .pNext = NULL,
    .flags = 0,
    .imageType = VK_IMAGE_TYPE_2D,
    .format = VK_FORMAT_B8G8R8A8_UNORM,
    .extent.width = actualSize,
    .extent.height = actualSize,
    .extent.depth = 1,
    .mipLevels = 1,
    .arrayLayers = 1,
    .samples = VK_SAMPLE_COUNT_1_BIT,
    .tiling = VK_IMAGE_TILING_OPTIMAL,
    .usage = VK_IMAGE_USAGE_TRANSFER_DST_BIT | VK_IMAGE_USAGE_STORAGE_BIT,
    .sharingMode = VK_SHARING_MODE_EXCLUSIVE,
    .queueFamilyIndexCount = 0,
    .pQueueFamilyIndices = NULL,
    .initialLayout = VK_IMAGE_LAYOUT_UNDEFINED
  };

  VkResult result = vkCreateImage(this->device, &createInfo, NULL,
      &this->image);
  if (result != VK_SUCCESS)
  {
    DEBUG_ERROR("Failed to create cursor image (VkResult: %d)", result);
    goto err;
  }

  struct VkMemoryRequirements memoryRequirements;
  vkGetImageMemoryRequirements(this->device, this->image,
      &memoryRequirements);

  this->imageMemory = vulkan_allocateMemory(this->memoryProperties,
      this->device, &memoryRequirements, VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
  if (!this->imageMemory)
    goto err_image;

  result = vkBindImageMemory(this->device, this->image, this->imageMemory,
      0);
  if (result != VK_SUCCESS)
  {
    DEBUG_ERROR("Failed to bind cursor image memory (VkResult: %d)", result);
    goto err_memory;
  }

  this->imageView = vulkan_createImageView(this->device, this->image,
      createInfo.format);
  if (!this->imageView)
    goto err_memory;

  this->stagingBuffer = vulkan_createBuffer(this->memoryProperties,
      this->device, actualSize * actualSize * 4,
      VK_BUFFER_USAGE_TRANSFER_SRC_BIT, &this->stagingMemory,
      &this->stagingMap);
  if (!this->stagingBuffer)
    goto err_image_view;

  this->imageSize = actualSize;
  return true;

err_image_view:
  vkDestroyImageView(this->device, this->imageView, NULL);
  this->imageView = NULL;

err_memory:
  vkFreeMemory(this->device, this->imageMemory, NULL);
  this->imageMemory = NULL;

err_image:
  vkDestroyImage(this->device, this->image, NULL);
  this->image = NULL;

err:
  return false;
}

bool vulkan_cursorInit(Vulkan_Cursor ** cursor,
    struct VkPhysicalDeviceMemoryProperties * memoryProperties, VkDevice device,
    VkCommandBuffer commandBuffer, VkDescriptorPool descriptorPool)
{
  *cursor = calloc(1, sizeof(**cursor));
  if (!*cursor)
  {
    DEBUG_ERROR("Failed to malloc Vulkan_Cursor");
    goto err;
  }

  LG_LOCK_INIT((*cursor)->lock);
  (*cursor)->memoryProperties = memoryProperties;
  (*cursor)->device = device;
  (*cursor)->commandBuffer = commandBuffer;
  (*cursor)->descriptorPool = descriptorPool;

  (*cursor)->computeShader = vulkan_loadShader(device,
      b_shader_cursor_rgb_comp_spv, b_shader_cursor_rgb_comp_spv_size - 1);
  if (!(*cursor)->computeShader)
    goto err_cursor;

  if (!createDescriptorSetLayout(*cursor))
    goto err_shader;

  (*cursor)->descriptorSet = vulkan_allocateDescriptorSet(device,
      (*cursor)->descriptorSetLayout, descriptorPool);
  if (!(*cursor)->descriptorSet)
    goto err_descriptor_set_layout;

  (*cursor)->pipelineLayout = vulkan_createPipelineLayout(device,
      (*cursor)->descriptorSetLayout);
  if (!(*cursor)->pipelineLayout)
    goto err_descriptor_set;

  (*cursor)->uniformBuffer = vulkan_createBuffer(memoryProperties, device,
      sizeof(struct UniformBuffer), VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT,
      &(*cursor)->uniformBufferMemory, &(*cursor)->uniformBufferMap);
  if (!(*cursor)->uniformBuffer)
    goto err_pipeline_layout;

  if (!createImage(*cursor))
    goto err_uniform;

  struct CursorPos  pos  = { .x = 0, .y = 0 };
  struct CursorPos  hs   = { .x = 0, .y = 0 };
  atomic_init(&(*cursor)->pos , pos );
  atomic_init(&(*cursor)->hs  , hs  );

  return true;

err_uniform:
  freeUniformBuffer(*cursor);

err_pipeline_layout:
  vkDestroyPipelineLayout(device, (*cursor)->pipelineLayout, NULL);

err_descriptor_set:
  vkFreeDescriptorSets(device, descriptorPool, 1, &(*cursor)->descriptorSet);

err_descriptor_set_layout:
  vkDestroyDescriptorSetLayout(device, (*cursor)->descriptorSetLayout, NULL);

err_shader:
  vkDestroyShaderModule(device, (*cursor)->computeShader, NULL);

err_cursor:
  LG_LOCK_FREE((*cursor)->lock);
  free(cursor);

err:
  return false;
}

void vulkan_cursorFree(Vulkan_Cursor ** cursor)
{
  Vulkan_Cursor * this = *cursor;
  if (!this)
    return;

  LG_LOCK_FREE(this->lock);
  if (this->data)
    free(this->data);

  freeImage(this);

  if (this->pipeline)
  {
    vkDestroyPipeline(this->device, this->pipeline, NULL);
    this->pipeline = NULL;
  }

  freeUniformBuffer(this);

  vkDestroyPipelineLayout(this->device, this->pipelineLayout, NULL);

  vkFreeDescriptorSets(this->device, this->descriptorPool, 1,
      &this->descriptorSet);

  vkDestroyDescriptorSetLayout(this->device, this->descriptorSetLayout, NULL);

  vkDestroyShaderModule(this->device, this->computeShader, NULL);

  free(this);
  *cursor = NULL;
}

bool vulkan_cursorInitPipeline(Vulkan_Cursor * this, VkRenderPass renderPass,
    VkColorSpaceKHR colorSpace)
{
  if (this->pipeline)
  {
    vkDestroyPipeline(this->device, this->pipeline, NULL);
    this->pipeline = NULL;
  }

  ShaderColorSpace shaderColorSpace;
  if (colorSpace == VK_COLOR_SPACE_EXTENDED_SRGB_LINEAR_EXT)
    shaderColorSpace = SHADER_COLOR_SPACE_EXTENDED_SRGB_LINEAR;
  else if (colorSpace == VK_COLOR_SPACE_HDR10_ST2084_EXT)
    shaderColorSpace = SHADER_COLOR_SPACE_HDR10_ST2084;
  else
    shaderColorSpace = SHADER_COLOR_SPACE_SRGB;

  uint32_t colorSpaceValue = shaderColorSpace;
  struct VkSpecializationMapEntry colorSpaceEntry =
  {
    .constantID = 0,
    .offset = 0,
    .size = sizeof(colorSpaceValue)
  };
  struct VkSpecializationInfo specializationInfo =
  {
    .mapEntryCount = 1,
    .pMapEntries = &colorSpaceEntry,
    .dataSize = sizeof(colorSpaceValue),
    .pData = &colorSpaceValue
  };

  struct VkComputePipelineCreateInfo createInfo =
  {
    .sType = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO,
    .pNext = NULL,
    .flags = 0,
    .stage.sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO,
    .stage.pNext = NULL,
    .stage.stage = VK_SHADER_STAGE_COMPUTE_BIT,
    .stage.module = this->computeShader,
    .stage.pName = "main",
    .stage.pSpecializationInfo = &specializationInfo,
    .layout = this->pipelineLayout,
    .basePipelineHandle = NULL,
    .basePipelineIndex = 0
  };

  VkResult result = vkCreateComputePipelines(this->device, NULL, 1, &createInfo,
      NULL, &this->pipeline);
  if (result != VK_SUCCESS)
  {
    DEBUG_ERROR("Failed to create compute pipeline (VkResult: %d)", result);
    return false;
  }

  return true;
}

bool vulkan_cursorSetShape(Vulkan_Cursor * this, const LG_RendererCursor type,
    const int width, const int height, const int stride, const uint8_t * data)
{
  LG_LOCK(this->lock);

  this->type   = type;
  this->width  = width;
  this->height = (type == LG_CURSOR_MONOCHROME ? height / 2 : height);
  this->stride = stride;

  const size_t size = height * stride;
  if (size > this->dataSize)
  {
    if (this->data)
      free(this->data);

    this->data = malloc(size);
    if (!this->data)
    {
      DEBUG_ERROR("Failed to malloc buffer for cursor shape");
      return false;
    }

    this->dataSize = size;
  }

  memcpy(this->data, data, size);
  this->update = true;

  LG_UNLOCK(this->lock);
  return true;
}

void vulkan_cursorSetState(Vulkan_Cursor * cursor, const bool visible,
    const float x, const float y, const float hx, const float hy)
{
  cursor->visible = visible;
  struct CursorPos pos = { .x = x , .y = y  };
  struct CursorPos hs  = { .x = hx, .y = hy };
  atomic_store(&cursor->pos, pos);
  atomic_store(&cursor->hs , hs);
}

static void updateImage(Vulkan_Cursor * this)
{
  if (this->type == LG_CURSOR_COLOR)
    memcpy(this->stagingMap, this->data, this->width * this->height * 4);
  else
  {
    DEBUG_ERROR("Cursor type %d not implemented", this->type);
    memset(this->stagingMap, 0xff, this->width * this->height * 4);
  }

  struct VkImageMemoryBarrier copyImageBarrier =
  {
    .sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER,
    .pNext = NULL,
    .srcAccessMask = VK_ACCESS_NONE,
    .dstAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT,
    .oldLayout = VK_IMAGE_LAYOUT_UNDEFINED,
    .newLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
    .srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED,
    .dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED,
    .image = this->image,
    .subresourceRange.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
    .subresourceRange.baseMipLevel = 0,
    .subresourceRange.levelCount = 1,
    .subresourceRange.baseArrayLayer = 0,
    .subresourceRange.layerCount = 1
  };

  vkCmdPipelineBarrier(this->commandBuffer, VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT,
      VK_PIPELINE_STAGE_TRANSFER_BIT, 0, 0, NULL, 0, NULL, 1,
      &copyImageBarrier);

  if (this->width != this->imageSize || this->height != this->imageSize)
  {
    union VkClearColorValue clearValue =
    {
      .float32 = {0.0f, 0.0f, 0.0f, 0.0f}
    };

    struct VkImageSubresourceRange range =
    {
      .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
      .baseMipLevel = 0,
      .levelCount = 1,
      .baseArrayLayer = 0,
      .layerCount = 1
    };

    vkCmdClearColorImage(this->commandBuffer, this->image,
        VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, &clearValue, 1, &range);

    copyImageBarrier.srcAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
    copyImageBarrier.oldLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;
    vkCmdPipelineBarrier(this->commandBuffer, VK_PIPELINE_STAGE_TRANSFER_BIT,
        VK_PIPELINE_STAGE_TRANSFER_BIT, 0, 0, NULL, 0, NULL, 1,
        &copyImageBarrier);
  }

  struct VkBufferImageCopy region =
  {
    .bufferOffset = 0,
    .bufferRowLength = 0,
    .bufferImageHeight = 0,
    .imageSubresource.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
    .imageSubresource.mipLevel = 0,
    .imageSubresource.baseArrayLayer = 0,
    .imageSubresource.layerCount = 1,
    .imageOffset.x = 0,
    .imageOffset.y = 0,
    .imageOffset.z = 0,
    .imageExtent.width = this->width,
    .imageExtent.height = this->height,
    .imageExtent.depth = 1
  };

  vkCmdCopyBufferToImage(this->commandBuffer, this->stagingBuffer, this->image,
      VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, 1, &region);

  struct VkImageMemoryBarrier renderImageBarrier =
  {
    .sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER,
    .pNext = NULL,
    .srcAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT,
    .dstAccessMask = VK_ACCESS_SHADER_READ_BIT,
    .oldLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
    .newLayout = VK_IMAGE_LAYOUT_GENERAL,
    .srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED,
    .dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED,
    .image = this->image,
    .subresourceRange.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
    .subresourceRange.baseMipLevel = 0,
    .subresourceRange.levelCount = 1,
    .subresourceRange.baseArrayLayer = 0,
    .subresourceRange.layerCount = 1
  };

  vkCmdPipelineBarrier(this->commandBuffer, VK_PIPELINE_STAGE_TRANSFER_BIT,
      VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT, 0, 0, NULL, 0, NULL, 1,
      &renderImageBarrier);
}

static void updateDescriptorSet(Vulkan_Cursor * this,
    VkImageView renderTargetImageView)
{
  struct VkDescriptorBufferInfo bufferInfo =
  {
    .buffer = this->uniformBuffer,
    .offset = 0,
    .range = VK_WHOLE_SIZE
  };

  struct VkDescriptorImageInfo renderTargetImageInfo =
  {
    .sampler = NULL,
    .imageView = renderTargetImageView,
    .imageLayout = VK_IMAGE_LAYOUT_GENERAL
  };

  struct VkDescriptorImageInfo cursorImageInfo =
  {
    .sampler = NULL,
    .imageView = this->imageView,
    .imageLayout = VK_IMAGE_LAYOUT_GENERAL
  };

  struct VkWriteDescriptorSet descriptorWrites[] =
  {
    {
      .sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET,
      .pNext = NULL,
      .dstSet = this->descriptorSet,
      .dstBinding = 0,
      .dstArrayElement = 0,
      .descriptorCount = 1,
      .descriptorType = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER,
      .pImageInfo = NULL,
      .pBufferInfo = &bufferInfo,
      .pTexelBufferView = NULL
    },
    {
      .sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET,
      .pNext = NULL,
      .dstSet = this->descriptorSet,
      .dstBinding = 1,
      .dstArrayElement = 0,
      .descriptorCount = 1,
      .descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_IMAGE,
      .pImageInfo = &renderTargetImageInfo,
      .pBufferInfo = NULL,
      .pTexelBufferView = NULL
    },
    {
      .sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET,
      .pNext = NULL,
      .dstSet = this->descriptorSet,
      .dstBinding = 2,
      .dstArrayElement = 0,
      .descriptorCount = 1,
      .descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_IMAGE,
      .pImageInfo = &cursorImageInfo,
      .pBufferInfo = NULL,
      .pTexelBufferView = NULL
    }
  };

  vkUpdateDescriptorSets(this->device, ARRAY_LENGTH(descriptorWrites),
      descriptorWrites, 0, NULL);
}

void updateUniformBuffer(Vulkan_Cursor * this, int width, int height)
{
  struct CursorPos  pos  = atomic_load(&this->pos );
  struct CursorPos  hs   = atomic_load(&this->hs  );

  pos.x -= hs.x;
  pos.y -= hs.y;

  struct UniformBuffer uniformBuffer = {
    .renderTargetSize = { width, height },
    .cursorPos = {
      (int32_t) lrintf((pos.x + 1.0f) * (float) width / 2.0f),
      (int32_t) lrintf((pos.y + 1.0f) * (float) height / 2.0f)
    }
  };

  memcpy(this->uniformBufferMap, &uniformBuffer, sizeof(uniformBuffer));
}

bool vulkan_cursorRender(Vulkan_Cursor * this, VkImageView renderTarget,
    LG_RendererRotate rotate, int width, int height)
{
  if (!this->visible)
    return true;

  if (rotate != LG_ROTATE_0)
    DEBUG_ERROR("Cursor rotation %d not implemented", rotate);

  if (this->update)
  {
    LG_LOCK(this->lock);
    this->update = false;

    if (!createImage(this))
    {
      LG_UNLOCK(this->lock);
      return false;
    }

    updateImage(this);

    LG_UNLOCK(this->lock);
  }

  updateUniformBuffer(this, width, height);

  updateDescriptorSet(this, renderTarget);

  vkCmdBindPipeline(this->commandBuffer, VK_PIPELINE_BIND_POINT_COMPUTE,
      this->pipeline);

  vkCmdBindDescriptorSets(this->commandBuffer,
      VK_PIPELINE_BIND_POINT_COMPUTE, this->pipelineLayout, 0, 1,
      &this->descriptorSet, 0, NULL);

  uint32_t groupCount = this->imageSize / 16;
  vkCmdDispatch(this->commandBuffer, groupCount, groupCount, 1);

  return true;
}
